-- V1__init.sql - PowerTrack initial schema + sample data

-- Tabelas
CREATE TABLE EQUIPMENT (
                           ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
                           NAME VARCHAR2(100) NOT NULL,
                           TYPE VARCHAR2(50),
                           LOCATION VARCHAR2(100)
);

CREATE TABLE ENERGY_METER (
                              ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
                              SERIAL_NUMBER VARCHAR2(50) NOT NULL,
                              INSTALLATION_DATE DATE
);

CREATE TABLE METER_READING (
                               ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
                               METER_ID NUMBER,
                               EQUIPMENT_ID NUMBER,
                               READING_TIMESTAMP TIMESTAMP (6) DEFAULT SYSTIMESTAMP,
                               ENERGY_KWH NUMBER(12,6),
                               POWER_KW NUMBER(12,6),
                               CONSTRAINT FK_METER FOREIGN KEY (METER_ID) REFERENCES ENERGY_METER(ID),
                               CONSTRAINT FK_READING_EQUIP FOREIGN KEY (EQUIPMENT_ID) REFERENCES EQUIPMENT(ID)
);

CREATE TABLE ALERT (
                       ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
                       EQUIPMENT_ID NUMBER,
                       MESSAGE VARCHAR2(400),
                       CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
                       CONSTRAINT FK_ALERT_EQUIP FOREIGN KEY (EQUIPMENT_ID) REFERENCES EQUIPMENT(ID)
);

-- Inserts: 5 registros mínimos por tabela
INSERT INTO EQUIPMENT (NAME, TYPE, LOCATION) VALUES ('Chiller Principal', 'Climatização', 'Bloco A');
INSERT INTO EQUIPMENT (NAME, TYPE, LOCATION) VALUES ('Compressor 01', 'Compressão', 'Bloco B');
INSERT INTO EQUIPMENT (NAME, TYPE, LOCATION) VALUES ('Iluminação Externa', 'Iluminação', 'Pátio');
INSERT INTO EQUIPMENT (NAME, TYPE, LOCATION) VALUES ('Bomba de Água', 'Hidrráulico', 'Subsolo');
INSERT INTO EQUIPMENT (NAME, TYPE, LOCATION) VALUES ('Servidor TI', 'TI', 'Data Center');

INSERT INTO ENERGY_METER (SERIAL_NUMBER, INSTALLATION_DATE) VALUES ('SN1001', SYSDATE);
INSERT INTO ENERGY_METER (SERIAL_NUMBER, INSTALLATION_DATE) VALUES ('SN1002', SYSDATE);
INSERT INTO ENERGY_METER (SERIAL_NUMBER, INSTALLATION_DATE) VALUES ('SN1003', SYSDATE);
INSERT INTO ENERGY_METER (SERIAL_NUMBER, INSTALLATION_DATE) VALUES ('SN1004', SYSDATE);
INSERT INTO ENERGY_METER (SERIAL_NUMBER, INSTALLATION_DATE) VALUES ('SN1005', SYSDATE);

-- Meter readings: referencing existing meter IDs and equipment IDs (insert order guarantees parents exist)
INSERT INTO METER_READING (METER_ID, EQUIPMENT_ID, READING_TIMESTAMP, ENERGY_KWH) VALUES (1, 1, SYSTIMESTAMP - INTERVAL '48' HOUR, 1.50);
INSERT INTO METER_READING (METER_ID, EQUIPMENT_ID, READING_TIMESTAMP, ENERGY_KWH) VALUES (1, 1, SYSTIMESTAMP - INTERVAL '24' HOUR, 2.10);
INSERT INTO METER_READING (METER_ID, EQUIPMENT_ID, READING_TIMESTAMP, ENERGY_KWH) VALUES (2, 2, SYSTIMESTAMP - INTERVAL '6' HOUR, 1.80);
INSERT INTO METER_READING (METER_ID, EQUIPMENT_ID, READING_TIMESTAMP, ENERGY_KWH) VALUES (3, 3, SYSTIMESTAMP - INTERVAL '1' HOUR, 3.20);
INSERT INTO METER_READING (METER_ID, EQUIPMENT_ID, READING_TIMESTAMP, ENERGY_KWH) VALUES (4, 4, SYSTIMESTAMP, 2.50);

INSERT INTO ALERT (EQUIPMENT_ID, MESSAGE) VALUES (1, 'Teste alerta 1 - consumo alto');
INSERT INTO ALERT (EQUIPMENT_ID, MESSAGE) VALUES (2, 'Teste alerta 2 - consumo alto');
INSERT INTO ALERT (EQUIPMENT_ID, MESSAGE) VALUES (3, 'Teste alerta 3 - consumo alto');
INSERT INTO ALERT (EQUIPMENT_ID, MESSAGE) VALUES (4, 'Teste alerta 4 - consumo alto');
INSERT INTO ALERT (EQUIPMENT_ID, MESSAGE) VALUES (5, 'Teste alerta 5 - consumo alto');

COMMIT;
