-- =============================================
-- Cria tabela de usuários para autenticação e segurança
-- =============================================

CREATE TABLE USERS (
                       ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       USERNAME VARCHAR2(50) UNIQUE NOT NULL,
                       PASSWORD VARCHAR2(200) NOT NULL,
                       ROLE VARCHAR2(20) NOT NULL
);

-- Insere usuários de exemplo
-- (em um ambiente real, as senhas seriam criptografadas)
INSERT INTO USERS (USERNAME, PASSWORD, ROLE) VALUES ('admin', '123', 'ADMIN');
INSERT INTO USERS (USERNAME, PASSWORD, ROLE) VALUES ('user', '123', 'USER');
