-- =========================================
-- POWERTRACK
-- =========================================

-- EQUIPMENT (equipamentos monitorados)

CREATE SEQUENCE EQUIPMENT_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE;

CREATE TABLE EQUIPMENT (
                           EQUIPMENT_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
                           NAME VARCHAR2(100) NOT NULL,
                           LOCATION VARCHAR2(100)
);

-- ENERGY_METER (medidores de energia)
CREATE TABLE ENERGY_METER (
                              METER_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
                              SERIAL_NUMBER VARCHAR2(50) NOT NULL,
                              INSTALLATION_DATE DATE
);

-- METER_READING (leituras do medidor)
CREATE TABLE METER_READING (
                               READING_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
                               METER_ID NUMBER,
                               EQUIPMENT_ID NUMBER,
                               READING_TIMESTAMP TIMESTAMP(6) DEFAULT SYSTIMESTAMP,
                               ENERGY_KWH NUMBER(12,6),
                               POWER_KW NUMBER(12,6),
                               CONSTRAINT FK_METER FOREIGN KEY (METER_ID) REFERENCES ENERGY_METER(METER_ID),
                               CONSTRAINT FK_READING_EQUIP FOREIGN KEY (EQUIPMENT_ID) REFERENCES EQUIPMENT(EQUIPMENT_ID)
);

-- ALERTS (alertas de consumo)
CREATE TABLE ALERTS (
                        ALERT_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
                        EQUIPMENT_ID NUMBER,
                        ALERT_TYPE VARCHAR2(50),
                        ALERT_MESSAGE VARCHAR2(400),
                        ALERT_TIMESTAMP TIMESTAMP DEFAULT SYSTIMESTAMP,
                        CONSTRAINT FK_ALERT_EQUIP FOREIGN KEY (EQUIPMENT_ID) REFERENCES EQUIPMENT(EQUIPMENT_ID)
);

-- =========================================
-- INSERTS
-- =========================================

-- EQUIPAMENTOS
INSERT INTO EQUIPMENT (NAME, LOCATION) VALUES ('Chiller Principal', 'Climatização');
INSERT INTO EQUIPMENT (NAME, LOCATION) VALUES ('Compressor 75', 'Compressão');
INSERT INTO EQUIPMENT (NAME, LOCATION) VALUES ('Iluminação Externa', 'Pátio');
INSERT INTO EQUIPMENT (NAME, LOCATION) VALUES ('Bomba de Água', 'Subsolo');
INSERT INTO EQUIPMENT (NAME, LOCATION) VALUES ('Servidor TI', 'Data Center');

-- MEDIDORES
INSERT INTO ENERGY_METER (SERIAL_NUMBER, INSTALLATION_DATE) VALUES ('SN1001', SYSDATE);
INSERT INTO ENERGY_METER (SERIAL_NUMBER, INSTALLATION_DATE) VALUES ('SN1002', SYSDATE);
INSERT INTO ENERGY_METER (SERIAL_NUMBER, INSTALLATION_DATE) VALUES ('SN1003', SYSDATE);
INSERT INTO ENERGY_METER (SERIAL_NUMBER, INSTALLATION_DATE) VALUES ('SN1004', SYSDATE);
INSERT INTO ENERGY_METER (SERIAL_NUMBER, INSTALLATION_DATE) VALUES ('SN1005', SYSDATE);

-- LEITURAS
INSERT INTO METER_READING (METER_ID, EQUIPMENT_ID, READING_TIMESTAMP, ENERGY_KWH, POWER_KW)
VALUES (1, 1, SYSTIMESTAMP - INTERVAL '48' HOUR, 1.50, 0.5);

INSERT INTO METER_READING (METER_ID, EQUIPMENT_ID, READING_TIMESTAMP, ENERGY_KWH, POWER_KW)
VALUES (1, 1, SYSTIMESTAMP - INTERVAL '24' HOUR, 2.10, 0.6);

INSERT INTO METER_READING (METER_ID, EQUIPMENT_ID, READING_TIMESTAMP, ENERGY_KWH, POWER_KW)
VALUES (2, 2, SYSTIMESTAMP - INTERVAL '6' HOUR, 1.80, 0.7);

INSERT INTO METER_READING (METER_ID, EQUIPMENT_ID, READING_TIMESTAMP, ENERGY_KWH, POWER_KW)
VALUES (3, 3, SYSTIMESTAMP - INTERVAL '1' HOUR, 33.20, 1.2);

INSERT INTO METER_READING (METER_ID, EQUIPMENT_ID, READING_TIMESTAMP, ENERGY_KWH, POWER_KW)
VALUES (4, 4, SYSTIMESTAMP, 2.50, 0.9);

-- ALERTAS
INSERT INTO ALERTS (EQUIPMENT_ID, ALERT_TYPE, ALERT_MESSAGE)
VALUES (1, 'CONSUMO', 'Consumo acima do limite esperado no Chiller Principal.');

INSERT INTO ALERTS (EQUIPMENT_ID, ALERT_TYPE, ALERT_MESSAGE)
VALUES (2, 'CONSUMO', 'Compressor 10 apresentou pico de energia.');

INSERT INTO ALERTS (EQUIPMENT_ID, ALERT_TYPE, ALERT_MESSAGE)
VALUES (3, 'CONSUMO', 'Iluminação externa consumindo energia fora do horário.');

INSERT INTO ALERTS (EQUIPMENT_ID, ALERT_TYPE, ALERT_MESSAGE)
VALUES (4, 'CONSUMO', 'Bomba de Água com uso prolongado.');

INSERT INTO ALERTS (EQUIPMENT_ID, ALERT_TYPE, ALERT_MESSAGE)
VALUES (5, 'CONSUMO', 'Servidor TI apresentou aumento repentino de carga.');

COMMIT;
