name: PowerTrack CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    name: Build e Testes
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do codigo
        uses: actions/checkout@v4

      - name: Configurar Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build com Maven
        run: mvn clean package -DskipTests

      - name: Executar Testes
        run: mvn test

      - name: Build da imagem Docker
        run: docker build -t powertrack:${{ github.sha }} .

      - name: Publicar JAR como artefato
        uses: actions/upload-artifact@v4
        with:
          name: powertrack-jar
          path: target/*.jar

  deploy-staging:
    name: Deploy Staging
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    environment: staging

    steps:
      - name: Checkout do codigo
        uses: actions/checkout@v4

      - name: Docker Compose Up Staging
        run: |
          MONGO_USERNAME=powertrack \
          MONGO_PASSWORD=powertrack123 \
          MONGO_DATABASE=powertrack \
          APP_PROFILE=staging \
          APP_PORT=8080 \
          docker compose up -d --build

      - name: Health Check Staging
        run: |
          sleep 40
          curl -u admin:123 -f http://localhost:8080/actuator/health

  deploy-producao:
    name: Deploy Producao
    runs-on: ubuntu-latest
    needs: deploy-staging
    if: github.ref == 'refs/heads/main'
    environment: producao

    steps:
      - name: Checkout do codigo
        uses: actions/checkout@v4

      - name: Docker Compose Up Producao
        run: |
          MONGO_USERNAME=powertrack \
          MONGO_PASSWORD=powertrack123 \
          MONGO_DATABASE=powertrack \
          APP_PROFILE=production \
          APP_PORT=80 \
          docker compose -f docker-compose.yml -f docker-compose.prod.yml up -d --build

      - name: Health Check Producao
        run: |
          sleep 40
          curl -u admin:123 -f http://localhost:80/actuator/health